article/urls.py
from django.urls import path
from django.contrib import admin
from . import views


app_name = "article"

urlpatterns = [
    path('frontend_test/', views.frontend_test, name="frontend_test"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('add_article/', views.add_article, name="add_article"),
    path('article/<int:id>/', views.detail, name="detail"),
    path('update/<int:id>/', views.update_article, name="update"),
    path('delete/<int:id>/', views.delete_article, name="delete"),
    path('',views.articles, name="articles"),
    path('comment/<int:id>', views.add_comment, name="comment")
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from article.views import index, index2, about,detail
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name="index"),
    path('index2', index2, name="index2"),
    path('about', about, name="about"),
    path('tinymce/', include('tinymce.urls')),
    path('article/<int:id>', detail, name="detail"),
    path('articles/', include("article.urls")),
    path('user/', include("user.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from django.contrib import admin
from . import views


app_name = "user"

urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', views.mylogin, name="login"),
    path('logout/', views.my_logout, name="logout"),
]

templates/includes/footer.html
<footer class="footer bg-dark fixed-bottom" style="height:3rem">
    <div class="container">
        <span class="text-muted">Reserved all right by Baran</span>
    </div>
</footer>

templates/includes/maps.html
<!DOCTYPE html>
<html>
  <head>
    <title>Simple Marker</title>
    <!-- The callback parameter is required, so we use console.debug as a noop -->
    <script async src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh7vnhdRH3_TnIJNa5Hj2DstdcqGbaXVs&callback=console.debug&libraries=maps,marker&v=beta">
    </script>
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      gmp-map {
        height: 100%;
      }

      /* Optional: Makes the sample page fill the window. */
      html,
      body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <gmp-map center="38.39347839355469,27.081466674804688" zoom="14" map-id="DEMO_MAP_ID">
      <gmp-advanced-marker position="38.39347839355469,27.081466674804688" title="My location"></gmp-advanced-marker>
    </gmp-map>
  </body>

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'index' %}">BaranBlog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
            aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'article:articles' %}">Makaleler </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Hakkımızda</a>
            </li>

        </ul>
        <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'article:dashboard' %}">Kontrol Paneli</a>
            </li>
            {% endif %}

            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user:logout' %}">Çıkış Yap</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user:login' %}">Giriş Yap</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user:register' %}">Kayıt Ol</a>
            </li>
            {% endif %}

        </ul>
    </div>
</nav>