article/urls.py
from django.urls import path
from django.contrib import admin
from . import views


app_name = "article"

urlpatterns = [
    path('frontend_test/', views.frontend_test, name="frontend_test"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('add_article/', views.add_article, name="add_article"),
    path('article/<int:id>/', views.detail, name="detail"),
    path('update/<int:id>/', views.update_article, name="update"),
    path('delete/<int:id>/', views.delete_article, name="delete"),
    path('',views.articles, name="articles"),
    path('comment/<int:id>', views.add_comment, name="comment")
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from article.views import index, index2, about,detail
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name="index"),
    path('index2', index2, name="index2"),
    path('about', about, name="about"),
    path('tinymce/', include('tinymce.urls')),
    path('article/<int:id>', detail, name="detail"),
    path('articles/', include("article.urls")),
    path('user/', include("user.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from tinymce import models as tinymce_models



# Create your models here.
class Article(models.Model):
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE, verbose_name="Yazar")
    title = models.CharField(max_length=50, verbose_name="Başlık")  # 50 stringlik boş bi karakter alanı tutuyo
    content = tinymce_models.HTMLField(verbose_name="İçerik")
    article_image = models.FileField(blank=True, null=True, verbose_name="Makaleye fotoğraf ekleyin.")
    created_date = models.DateTimeField(auto_now_add=True)  # autonow add oluşturulma tarihini güncel tarih yapıyor


    def __str__(self):
        return self.title

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name="comments")
    comment_author = models.CharField(max_length=50,verbose_name="isim")
    comment_content = tinymce_models.HTMLField(max_length=200, verbose_name="Yorum")
    comment_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment_content

    class Meta:
        ordering = ['-comment_date']

# from django.contrib.auth.models import User\n",
#     "from article.models import Article\n",
#     "newUser = User(username=\"denemekullanici\",password=\"123\")\n",
#     "newUser\n",

article/forms.py
from django.forms import ModelForm
from .models import Article, Comment
from tinymce.widgets import TinyMCE
class ArticleForm(ModelForm):
    class Meta:
        model = Article
        # fields = "__all__"
        exclude = ["author"]
        widgets = {'content': TinyMCE(attrs={'cols': 80, 'rows': 30})}

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = "__all__"
        widgets = {'comment_content': TinyMCE(attrs={'cols': 80, 'rows': 30})}

article/views.py
from django.db.models import Q
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.urls import reverse

from article.forms import ArticleForm, CommentForm
from article.models import Article, Comment


# Create your views here.

def index(request):
    context = {"isim": "Baran",
               "yas": 25,
               "numbers": [1, 2, 3, 4, 5, 6, 7, 8],
               "coffees": {"latte": 25, "americano": 30, "çay": 15, "filtre kahve": 35}
               }
    return render(request, "index.html", context)


def index2(request):
    return render(request, "index2.html")


def detail(request, id):
    article = get_object_or_404(Article, id=id)
    comments = article.comments.all()
    form = CommentForm()
    # article = Article.objects.filter(id=id).first()
    context = {
        "article": article,
        "comments":comments,
        "form": form,
    }
    return render(request, "detail.html", context)


def about(request):
    return render(request, "about.html")


def frontend_test(request):
    users = User.objects.all()
    return render(request, "frontend.html", context={"users": users})


@login_required(login_url="user:login")
def dashboard(request):
    articles = Article.objects.all()
    context = {
        "articles": articles
    }
    return render(request, "dashboard.html", context)


@login_required
def add_article(request):
    form = ArticleForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        # author = form.cleaned_data.get("author")
        # title = form.cleaned_data.get("title")
        #
        # article = Article()
        # article.author = author
        # article.title = title
        # article.save()
        article = form.save(commit=False)  ##veritabanına gerçek bi save işlemi yapmamış oluyoruz.
        article.author = request.user
        article.save()

        messages.success(request, "Makaleniz başarıyla kaydedildi.")
        return redirect("article:dashboard")

    context = {
        "form": form
    }
    return render(request, "add_article.html", context)


@user_passes_test(lambda u: u.is_superuser)
def update_article(request, id):
    article = get_object_or_404(Article, id=id)
    form = ArticleForm(request.POST or None, request.FILES or None, instance=article)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()  # commit = True

        messages.success(request, "Makale başarıyla güncellendi.")
        return redirect("article:dashboard")
    return render(request, "update.html", {"form": form})


def delete_article(request, id):
    article = get_object_or_404(Article, id=id)
    article.delete()

    messages.success(request, "Makale başarıyla silindi.")
    return redirect("article:dashboard")


def articles(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(Q(title__icontains=keyword) | Q(content__contains=keyword))
        return render(request, "articles.html", {"articles": articles})
    articles = Article.objects.all()

    return render(request, "articles.html", {"articles": articles})


def add_comment(request, id):
    article = get_object_or_404(Article, id=id)
    form = CommentForm(request.POST or None)
    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")
        new_comment = Comment()
        new_comment.comment_author = comment_author
        new_comment.comment_content = comment_content
        new_comment.article = article
        new_comment.save()
    # if form.is_valid():
    #     new_comment = form.save(commit=False)
    #     new_comment.comment_author = request.user
    #     new_comment.save()

    return redirect(reverse("article:detail", kwargs={"id": id}))

templates/about.html
{% extends "layout.html" %}
{% block body %}
<h3>Hakkımızda</h3>
<hr>
<p>Selamlar Ben Baran</p>
{% endblock body %}

templates/add_article.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <form style="padding-top:20px;" method="post" enctype="multipart/form-data">
            <h3>Makale Oluştur</h3>
            <hr>
            {% csrf_token %}
            {{ form.media }}
            {{ form|crispy }}
            <br>
            <button type="submit" class="btn btn-success">Oluştur</button>
        </form>
    </div>
</div>



{% endblock body %}

templates/articles.html
{% extends 'layout.html' %}
{% block body %}


<div class="row">
    <div class="col-lg-8 offset-2" style="text-align:center">
          <h3 style="margin:10px auto">Makaleler</h3>
            <hr>
        <form action="" method="GET">
            {% csrf_token %}
            <input type="text" name="keyword" class="input-sm">
            <button type="submit" class="btn btn-danger">Ara </button>
            <hr>
        </form>
    </div>
</div>



{% if articles %}
{% for article in articles %}
<div class="row">
                <div class="col-lg-8 offset-2">
                    <!-- Post content-->
                    <article>
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <a href="{% url 'article:detail' article.id %}">
                            <h1 class="fw-bolder mb-1">{{ article.title }}</h1></a>
                            <!-- Post meta content-->
                            <div class="text-muted fst-italic mb-2">Posted on {{article.created_date}}</div>
                            <!-- Post categories-->

                        </header>
                        <!-- Preview image figure-->
                        {% if article.article_image %}
                        <figure class="mb-4"><img class="img-fluid rounded" src="{{ article.article_image.url }}" alt="..."></figure>
                        {% endif %}
                        <!-- Post content-->
                        <section class="mb-5">
                            <div>
                                {{ article.content|safe|truncatewords:30 }}
                                <a href="{% url 'article:detail' article.id %}">
                                    read more
                            </a>
                            </div>
                        </section>
                    </article>

                </div>
            </div>
<hr>
{% endfor %}

{% else %}
<div class="row">
    <div class="col-lg-8 offset-2">
<div class="alert alert-danger" role="alert">
    Makale bulunamadı!
</div>
</div>
    </div>

{% endif %}
<script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}
{% block body %}
<h3>Kontrol Paneli Sayfası</h3>
<p>
    Hoşgeldiniz, <small> {{request.user.username}} </small>
</p>

<hr>
{% if articles %}
<table style="font-size: 12px" class="table table-striped table-dark">
    <thead>
    <tr>
        <th scope="col">ID</th>
        <th scope="col">Yazar</th>
        <th scope="col">Başlık</th>
        <th scope="col">Tarih</th>
        <th scope="col">Güncelle</th>
        <th scope="col">Sil</th>

    </tr>
    </thead>
    <tbody>
    {% for article in articles %}
    <tr>
        <td>{{ article.id }}</td>
        <td>{{ article.author }}</td>
        <td><a href="{% url 'article:detail' article.id %}">{{ article.title}}</a></td>
        <td>{{ article.created_date }}</td>
        <td><a href="{% url 'article:update' article.id %}" class="btn btn-warning">Güncelle</a></td>
        <td><a href="{% url 'article:delete' article.id %}" class="btn btn-danger">Sil</a></td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<div class="alert alert-danger" role="alert">
    Henüz bir makaleniz bulunmuyor.
</div>
{% endif %}
<hr>
<a href="{% url 'article:add_article' %}" class="btn btn-danger">Makale ekle</a>

{% endblock body %}

templates/detail.html
{% extends "layout.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block body %}


<div class="row">
                <div class="col-lg-8 offset-2">
                    <!-- Post content-->
                    <article>
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <h1 class="fw-bolder mb-1">{{ article.title }}</h1>
                            <!-- Post meta content-->
                            <div class="text-muted fst-italic mb-2">Posted on {{article.created_date}}</div>
                            <!-- Post categories-->

                        </header>
                        <!-- Preview image figure-->
                        {% if article.article_image %}
                        <figure class="mb-4"><img class="img-fluid rounded" src="{{ article.article_image.url }}" alt="..."></figure>
                        {% endif %}
                        <!-- Post content-->
                        <section class="mb-5">
                            <p class="fs-5 mb-4">{{ article.content|safe }} </p>

                        </section>
                    </article>
<section class="mb-5">
                        <div class="card bg-light">
                            <div class="card-body">
                                <!-- Comment form-->
                                <form class="mb-4" method="POST" action="{% url 'article:comment' article.id %}" >
                                    {% csrf_token %}
                                      <div class="form-group">
                                        <label for="exampleInputEmail1">Yazar</label>
                                        <input type="text" name="comment_author" class="form-control" id="exampleInputEmail1" aria-describedby="yazarHelp" placeholder="Yazar İsmi">

                                      </div>
                                        <div class="form-group">
                            <label >Yorum:</label>
                            <textarea class="form-control" rows="8" name="comment_content"
                                  placeholder="Yorumunuzu Bırakın!"
                                  data-sider-insert-id="3397cf06-3701-48fe-ae6b-569ca16c0cb5"
                                  data-sider-select-id="cab454df-7321-44da-a1f8-8bd3a783d2bc"></textarea>
                        </div>
                                    <button class="btn btn-danger" type="submit">Ekle</button>

                                </form>
                                <!-- Comment with nested comments-->
                                {% for comment in comments %}
                                        <div class="d-flex mb-4">
                                            <!-- Parent comment-->
                                            <div class="flex-shrink-1"><img class="rounded-circle mr-3" style="width:50px; margin:10px"
                                                                            src="{% static 'avatar.png' %}" alt="...">
                                            </div>
                                            <div class="ms-3">
                                                <div class="fw-bold"> <b> {{comment.comment_author}}</b>
                                                <br>
                                                    <sup>{{ comment.comment_date }}  </sup>
                                                </div>
                                                {{ comment.comment_content }}
                                        </div>
                </div>
                                {% endfor %}
                            </div>


                                </div>
</section>
                            </div>
</div>
                        </div>
                    </section>
                </div>

            </div>
{% endblock body %}

templates/frontend.html
<!doctype html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Frontend_test</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- bootstrap kodları kimi CSS kodlarının çalışmasına mani olabilir -->

    <link rel="shortcut icon" href="https://icons8.com/icon/XAuXRpisoL2i/lizard"
          type="image/x-icon" color="#000000">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Tac+One&display=swap" rel="stylesheet">

    <!-- external css -->
    <!--    <link rel="stylesheet" href="{% static 'frontend.css' '%}">-->

    <!-- internal css -->
    <style>
        .yeni-biseyler{
        background:yellow
        }
        tr:nth-child(even){
            background-color: blue !important
            }

         /* th {
         background: lightblue !important
         }
         td {
         background:pink  !important
         } */

        table, td, th {
            border: 5px solid black;
            border-radius: 8px;
            padding: 20px;
            border-collapse: collapse;
            text-align: center;
        }
        .mycontainer{
            width:100%;
            overflow:auto;
        }
        .mycontainer div {
            width:33%;
            float:left;

        }
        .mycontainer h2,.mycontainer p{
            padding-left:10px;
            padding-right:10px;
            color:purple
        }
        .city{
            background: brown;
            color: orange;
            padding: 10px;
        }

        .country {
            text-align:center;
            border: groove;
            border-collapse: collapse;
         }
         #benimBasligim {
            color: yellow;
            background: gray;
            font-family: Brush Script MT;

        }

        .tac-one-regular {
          font-family: "Tac One", sans-serif;
          font-weight: 400;
          font-style: normal;
        }

    </style>
</head>
<body>
<div class="container">
  <div class="row">
    <div class="col">
      Column
    </div>
    <div class="col">
      Column
    </div>
    <div class="col">
      Column
    </div>
  </div>
</div>

<div>
<!--<table class="table">-->
<!--    <thead>-->
<!--    <tr>-->
<!--        <th scope="col">#</th>-->
<!--        <th scope="col"> Firstname</th>-->
<!--        <th scope="col">Lastname</th>-->
<!--        <th scope="col">Username</th>-->
<!--    </tr>-->
<!--    </thead>-->

<!--    <tbody>-->
<!--    {% for user in users %}-->
<!--    <tr>-->
<!--        <th scope="row"> {{user.id}}</th>-->
<!--        <td> {{user.first_name}}</td>-->
<!--        <td> {{user.last_name}}</td>-->
<!--        <td>{{ user.username}}</td>-->
<!--    </tr>-->
<!--    {% endfor %}-->
<!--    </tbody>-->
<!--</table>-->


<h1 class="yeni-biseyler">Benim Birinci Başlığım</h1>

<p style="background:gray">Bu benim paragrafım</p>

<a href="https://www.coingecko.com/en/coins/dream-machine-token" style="color: #ff9f00;font-size: larger"
   target="_blank"> CoinGecko</a>

<a href="mailto:baran.acidere@gmail.com">Send mail </a>

<button onclick="javascript:window.open('https://www.youtube.com/watch?v=dmbglpJndkY','blank')" formtarget="_blank">
    Drum&Bass
</button>

<br> <!-- br etiketi satır atlamayı sağlıyor -->
<hr> <!-- horizontal rule, çok ince bir gri çizgi -->
<img src="{% static 'Unknown.jpeg' %}" alt="Ev resmi">

<!--inline css -->
<!--<tagname style="property:value;"-->

<section>
<!-- etiket denemeleri -->
<!--<b> BARAN</b>-->
<!--<br> &lt;!&ndash; br etiketi satır atlamayı sağlıyor &ndash;&gt;-->
<!--<strong>ACIDERE</strong>-->
<!--<i>MERHABA</i>-->
<!--<em>BENİ VURGULA</em>-->
<!--<mark> Marked text</mark>-->
<!--<small>KÜÇÜK YAZI</small>-->
<!--<del>ÜSTÜ ÇİZİLİ YAZI</del>-->
<!--<ins>ALTI ÇİZİLİ YAZI</ins>-->
<!--<sub>ALT TEXT</sub>-->
<!--<sup> ÜST</sup>-->
<!--<blockquote cite="https://www.tradingview.com/symbols/BTCUSDT/">-->
<!--    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, consectetur deleniti dolorum eaque earum eius id-->
<!--    neque nostrum placeat quas repudiandae sapiente totam. Assumenda iure nam nihil nulla sapiente soluta.-->
<!--    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad amet at beatae corporis culpa eligendi eos expedita-->
<!--    fugiat fugit impedit inventore itaque nesciunt, officiis omnis quasi quidem tenetur voluptates voluptatum?-->
<!--    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi aperiam aspernatur culpa deserunt eius, enim-->
<!--    inventore ipsa iusto laboriosam laborum minus, nam necessitatibus nesciunt placeat ratione reprehenderit sit-->
<!--    temporibus vero!-->
<!--    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias ipsam nesciunt repellendus. Commodi distinctio-->
<!--    ducimus error molestias optio provident, suscipit ullam. Aliquid dolorum earum inventore magni, mollitia quasi qui-->
<!--    ut.-->
<!--</blockquote>-->


<!--&lt;!&ndash; inline css &ndash;&gt;-->
<!--<h1 style="background-color:DodgerBlue; color:white;border: 15px dotted palevioletred; border-radius: 15px; padding: 15px;text-align:center">-->
<!--    DENEME DENEME</h1>-->
<!--<p style="color:red; background:cyan; font-weight:bold"> SEÇİMİ KAZANDIK</p>-->
<!--&lt;!&ndash;h1&ndash;&gt;-->
<!--&lt;!&ndash;h2&ndash;&gt;-->
<!--&lt;!&ndash;h3&ndash;&gt;-->
<!--&lt;!&ndash;h4&ndash;&gt;-->
<!--&lt;!&ndash;h5&ndash;&gt;-->
<!--&lt;!&ndash;h6&ndash;&gt;-->
<!--<table style="width:100%">-->
<!--    <tr>  &lt;!&ndash; satır elementi&ndash;&gt;-->
<!--        <th style="width:70%"> Company</th>   &lt;!&ndash; başlıklar &ndash;&gt;-->
<!--        <th colspan="2"> Contact and Country</th>-->
<!--        &lt;!&ndash;<th> Country</th>  sütunları birleştirmek için commente aldık &ndash;&gt;-->
<!--    </tr>-->

<!--    <tr>-->
<!--        <td> Mercedes</td> &lt;!&ndash; rowspan="2" satır birleştirmeye yarıyor. &ndash;&gt;-->
<!--        <td> Hans Meier</td>-->
<!--        <td>Germany</td>-->
<!--    </tr>-->

<!--    <tr style="height:200px">-->
<!--        <td> Skoda</td>-->
<!--        <td> Olga Naie</td>-->
<!--        <td> Czech Republic</td>-->
<!--    </tr>-->
<!--</table>-->

<!--<ul>-->
<!--    <li> Hülya</li>-->
<!--    <li> Mehmet</li>-->
<!--    <li>Baran</li>-->
<!--    <li>Selçuk</li>-->
<!--</ul>-->


<!--&lt;!&ndash; ordered list &ndash;&gt;-->
<!--<ol>-->
<!--    <li> Mehmet</li>-->
<!--    <li>Baran</li>-->
<!--    <li>Selçuk</li>-->
<!--</ol>-->

<!--<dl>-->
<!--    <dt>Mantı</dt>-->
<!--    <dd> - Mantı Kayseri'nin meşhur yemeğidir, hamur ve kıyma ile yapılır.</dd>-->
<!--    <dt> Makarna</dt>-->
<!--    <dd> - Sarımsaklı yoğurtlu makarna çok iyidir.</dd>-->
<!--</dl>-->
<!--<ul style="list-style-type:circle">  &lt;!&ndash; circle square ya da disc kullanabiliriz.&ndash;&gt;-->
<!--    <li> Mehmet</li>-->
<!--    <li>Baran</li>-->
<!--    <li>Selçuk</li>-->
<!--</ul>-->

<!--<ol type="a">-->
<!--    &lt;!&ndash; I, A, 5 vs. verebiliriz.bu sıralama tipini değiştircektir. Sayı verdiğimizde o sayıdan sıralamaya başlayacak.&ndash;&gt;-->
<!--    <li> Mehmet</li>-->
<!--    <li>Baran</li>-->
<!--    <li>Selçuk</li>-->
<!--</ol>-->

<!--<div  style="background:lightyellow; width:300px; margin:auto" >-->
<!--    <h2>Londra</h2>-->
<!--    <p>Londra, İngiltere'nin başkentidir.</p>-->
<!--    <p>Londra'da 13 milyon insan yaşar.</p>-->
<!--</div>-->

<!--<div class="mycontainer">  &lt;!&ndash;bu classı yukarıdaki style etiketi içerisinde tanımlıyoruz.(internal css) &ndash;&gt;-->
<!--    <div style="background:lightyellow">-->
<!--        <h2>Londra</h2>-->
<!--        <p>Londra, İngiltere'nin başkentidir.</p>-->
<!--        <p>Londra'da 13 milyon insan yaşar.</p>-->
<!--    </div>-->
<!--    <div style="background:lightblue">-->
<!--        <h2>İstanbul</h2>-->
<!--        <p>İstanbul Türkiye'nin en büyük şehridir.</p>-->
<!--        <p>İstanbul'da 18 milyon insan yaşar.</p>-->
<!--    </div>-->
<!--    <div style="background:lightgray">-->
<!--        <h2>İzmir</h2>-->
<!--        <p>İzmir Türkiye'nin bir şehridir.</p>-->
<!--        <p>İzmir'de 5 milyon insan yaşar.</p>-->
<!--    </div>-->
<!--</div>-->
<!--&lt;!&ndash;  ul>li.item$*5    taba basarsak emmetin nasıl tamamladığını görebiliriz.&ndash;&gt;-->

<!--<h2 class="city country">Karaman</h2>-->
<!--<p>Karaman, İç Anadolu bölgesindedir.</p>-->
<!--<h2 class="city">Artvin</h2>-->
<!--<p> Artvin, Karadeniz bölgesindedir</p>-->
</section>

<h1 id="benimBasligim"> Başlık Deneme</h1>
<h1 class="tac-one-regular"> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque beatae dolor dolore minus nemo, nesciunt odio pariatur perferendis praesentium quibusdam quos sequi similique temporibus! Blanditiis culpa doloremque fuga illo unde.</h1>
<!--yukarıdaki kodu google-fonttan alıp headera ekledik.-->
<i class="fa-solid fa-hippo"></i>
    </div>

 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>



</html>

templates/home.html
{% extends "layout.html" %}

{% block body %}

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

{% endblock body %}

templates/index.html
{% extends "layout.html" %}
{% block body %}

<p>{% if request.user.is_authenticated %}
    giriş yapılmış, {{request.user.username}}
    {% else %}
    giriş yapılmamış
    {% endif %}</p>


{% endblock body %}

templates/index2.html
{% extends "layout.html" %}
{% block body %}

<h2>asfdsfsg</h2>

{% endblock body %}

templates/layout.html
<!doctype html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>BaranBlog</title>
<!--    <link rel="stylesheet" href="static/style2.css">-->
    <!--    <link rel = "stylesheet" href="static/style2.css">-->
    <link rel="stylesheet" href="{% static 'css/bootstrap4_0_0.css'%}">
<!--    <script src="https://cdn.tiny.cloud/1/52o0f792eh2myfn3xhzftvtc69s72gzev90taiu6kz21nj2s/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>-->
<!--    <script>-->
<!--        tinymce.init({-->
<!--    selector:"textarea"-->
<!--        })-->
<!--    </script>-->
</head>
<body>
{% include "includes/navbar.html" %}
<div class="container" style="margin-bottom:10rem">   <!--sayfanın altına sabit blok koymak için-->
    {% if messages %}
    {% for message in messages %}

        <div {% if message.tags %} class="alert alert-{{ message.tags }} mt-3" {% endif %} role="alert">
      {{ message }}
    </div>
    {% endfor %}

    {% endif %}


    {% block body %}


    {% endblock body %}
</div>


{% include 'includes/footer.html' %}

<!--    <img src = "{% static 'Bronzino-Neptune.jpg' %}" alt = "my image" >-->
<script src="{% static 'js/jquery3_2_1.js' %}"></script>
<!--<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"-->
<!--        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"-->
<!--        crossorigin="anonymous"></script>-->

<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>

</html>